name: 'Build'
description: 'Build project'
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build app
        run: npm ci && npm run build
